import React, { useState, useMemo, useCallback } from 'react';
import { Check, X, ChevronRight, AlertTriangle, Activity, Stethoscope, Maximize2 } from 'lucide-react';
import TwelveLead from './TwelveLead.jsx';
import { synth12 } from './synth.js';
import { CASES } from './cases.js';

const L = {
  title: { es: '12 derivaciones', en: '12-lead', pt: '12 derivações' },
  caseOf: { es: (a, b) => `Caso ${a} de ${b}`, en: (a, b) => `Case ${a} of ${b}`, pt: (a, b) => `Caso ${a} de ${b}` },
  years: { es: 'años', en: 'years old', pt: 'anos' },
  male: { es: 'Hombre', en: 'Man', pt: 'Homem' },
  female: { es: 'Mujer', en: 'Woman', pt: 'Mulher' },
  hr: { es: 'FC', en: 'HR', pt: 'FC' },
  bp: { es: 'PA', en: 'BP', pt: 'PA' },
  spo2: { es: 'SatO₂', en: 'SpO₂', pt: 'SatO₂' },
  rr: { es: 'FR', en: 'RR', pt: 'FR' },
  question: { es: '¿Qué muestra este electrocardiograma?', en: 'What does this electrocardiogram show?', pt: 'O que mostra este eletrocardiograma?' },
  correct: { es: 'Correcto', en: 'Correct', pt: 'Correto' },
  incorrect: { es: 'Incorrecto', en: 'Incorrect', pt: 'Incorreto' },
  wasAnswer: { es: 'La respuesta era', en: 'The answer was', pt: 'A resposta era' },
  why: { es: 'Por qué', en: 'Why', pt: 'Por quê' },
  pitfall: { es: 'El error frecuente', en: 'The common trap', pt: 'O erro frequente' },
  action: { es: 'Conducta', en: 'Management', pt: 'Conduta' },
  next: { es: 'Siguiente caso →', en: 'Next case →', pt: 'Próximo caso →' },
  restart: { es: 'Empezar de nuevo', en: 'Start over', pt: 'Começar de novo' },
  paper: { es: 'Papel', en: 'Paper', pt: 'Papel' },
  dark: { es: 'Oscuro', en: 'Dark', pt: 'Escuro' },
  tapLead: { es: 'Tocá una derivación para ampliarla', en: 'Tap a lead to enlarge it', pt: 'Toque numa derivação para ampliá-la' },
  swipe: { es: '← Deslizá para ver las precordiales (V1 a V6)', en: '← Swipe to see the precordial leads (V1 to V6)', pt: '← Deslize para ver as precordiais (V1 a V6)' },
  close: { es: 'Cerrar', en: 'Close', pt: 'Fechar' },
  done: { es: 'Terminaste las ocho', en: 'You finished all eight', pt: 'Você terminou os oito' },
  doneSub: {
    es: 'Estos trazados son sintéticos: los genera un modelo del vector eléctrico del corazón. Sirven para entrenar la localización, que es lo que una sola derivación no puede enseñar.',
    en: 'These tracings are synthetic, generated by a model of the heart’s electrical vector. They train localization, which a single lead cannot teach.',
    pt: 'Estes traçados são sintéticos: gerados por um modelo do vetor elétrico do coração. Servem para treinar a localização, que uma única derivação não pode ensinar.',
  },
  synthetic: {
    es: 'Trazado generado por modelo vectorial',
    en: 'Tracing generated by a vector model',
    pt: 'Traçado gerado por modelo vetorial',
  },
  score: { es: 'Aciertos', en: 'Correct', pt: 'Acertos' },
};

// El electro es ancho por naturaleza: 250 mm de papel. En un celular eso obliga a
// elegir entre achicarlo hasta que no se lea o dejar scroll horizontal. Se elige
// el scroll, que es lo que hace cualquiera con un electro impreso, y además se
// permite tocar una derivación para verla sola y en grande.
function EcgSheet({ signal, theme, highlight, lang, onLeadClick }) {
  return (
    <div className="rounded-2xl overflow-hidden border border-slate-800 bg-slate-950">
      <div className="relative">
        <div className="overflow-x-auto">
          <div className="min-w-[680px]">
            <TwelveLead signal={signal} theme={theme} highlight={highlight} onLeadClick={onLeadClick} />
          </div>
        </div>
        {/* Degradado en el borde derecho: en mobile el electro no entra entero y sin
            esta señal el usuario no sabe que puede desplazarlo. Desaparece a partir
            de sm:, donde ya entra completo. */}
        <div className="sm:hidden pointer-events-none absolute inset-y-0 right-0 w-7 bg-gradient-to-l from-slate-950/55 to-transparent" />
      </div>
      <div className="flex items-center justify-between gap-2 px-3 py-2 border-t border-slate-800/80">
        <span className="text-[10px] text-slate-600 font-mono uppercase tracking-wider truncate">{L.synthetic[lang]}</span>
        <span className="flex items-center gap-1 text-[10px] text-slate-500 flex-shrink-0">
          <Maximize2 className="w-3 h-3" /><span className="hidden xs:inline sm:inline">{L.tapLead[lang]}</span>
        </span>
      </div>
      <p className="sm:hidden px-3 pb-2 text-[10px] text-slate-500">{L.swipe[lang]}</p>
    </div>
  );
}

// Una sola derivación, a todo lo ancho y con el doble de alto: para mirar de
// cerca el segmento ST cuando la vista general no alcanza.
function LeadZoom({ signal, lead, theme, lang, onClose }) {
  const single = useMemo(() => ({
    fs: signal.fs,
    duration: signal.duration,
    leads: { [lead]: signal.leads[lead] },
    labels: [lead],
  }), [signal, lead]);

  return (
    <div className="fixed inset-0 z-[180] bg-black/80 flex items-center justify-center p-4" onClick={onClose}>
      <div className="w-full max-w-3xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-2">
          <span className="font-mono text-lg text-indigo-300 font-bold">{lead}</span>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-200 text-sm">{L.close[lang]}</button>
        </div>
        <div className="rounded-2xl overflow-hidden border border-slate-700">
          <TwelveLead signal={single} theme={theme} rhythmLead={lead} singleRow />
        </div>
      </div>
    </div>
  );
}

export default function TwelveLeadSection({ lang = 'es', onAnswer }) {
  const [idx, setIdx] = useState(0);
  const [picked, setPicked] = useState(null);
  const [theme, setTheme] = useState('paper');
  const [zoomLead, setZoomLead] = useState(null);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);

  const c = CASES[idx];
  // El trazado se genera una vez por caso, no en cada render: son 30.000 muestras
  // y regenerarlo al tocar un botón se nota en el celular.
  const signal = useMemo(() => synth12({ ...c.signal, fs: 250, duration: 10 }), [c]);

  const answered = picked !== null;
  const isRight = answered && picked === c.answer;

  const pick = useCallback((id) => {
    if (answered) return;
    setPicked(id);
    const right = id === c.answer;
    if (right) setScore((s) => s + 1);
    if (onAnswer) onAnswer(right, c.id);
  }, [answered, c, onAnswer]);

  const next = useCallback(() => {
    if (idx + 1 >= CASES.length) { setFinished(true); return; }
    setIdx(idx + 1);
    setPicked(null);
    setZoomLead(null);
  }, [idx]);

  const restart = useCallback(() => {
    setIdx(0); setPicked(null); setScore(0); setFinished(false); setZoomLead(null);
  }, []);

  if (finished) {
    return (
      <div className="text-center py-12 space-y-4">
        <div className="w-14 h-14 mx-auto rounded-2xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center">
          <Check className="w-7 h-7 text-emerald-400" />
        </div>
        <h2 className="font-display text-2xl text-slate-100">{L.done[lang]}</h2>
        <p className="text-3xl font-mono text-indigo-300">{score} / {CASES.length}</p>
        <p className="text-slate-500 text-sm max-w-md mx-auto leading-relaxed">{L.doneSub[lang]}</p>
        <button onClick={restart}
          className="px-6 py-3 rounded-xl bg-indigo-700 hover:bg-indigo-600 text-white font-bold transition-colors">
          {L.restart[lang]}
        </button>
      </div>
    );
  }

  const sexLabel = c.sex === 'F' ? L.female[lang] : L.male[lang];

  return (
    <div className="space-y-4">
      {/* Cabecera: progreso, aciertos y tema del papel */}
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <span className="font-mono text-[11px] text-slate-500 uppercase tracking-widest">
            {L.caseOf[lang](idx + 1, CASES.length)}
          </span>
          <span className="font-mono text-[11px] text-slate-600">
            {L.score[lang]} {score}/{idx + (answered ? 1 : 0)}
          </span>
        </div>
        <div className="flex gap-1 p-0.5 bg-slate-900/70 border border-slate-800 rounded-lg">
          {['paper', 'dark'].map((th) => (
            <button key={th} onClick={() => setTheme(th)}
              className={`px-2.5 py-1 rounded text-[11px] font-medium transition-colors ${theme === th ? 'bg-slate-800 text-indigo-300' : 'text-slate-500 hover:text-slate-300'}`}>
              {L[th][lang]}
            </button>
          ))}
        </div>
      </div>

      {/* Presentación clínica */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/40 p-4 space-y-3">
        <div className="flex items-center gap-2 text-indigo-300">
          <Stethoscope className="w-4 h-4" />
          <span className="text-sm font-semibold">{sexLabel}, {c.age} {L.years[lang]}</span>
        </div>
        <p className="text-slate-300 text-sm leading-relaxed">{c.stem[lang]}</p>
        <div className="flex flex-wrap gap-2">
          {[['hr', c.vitals.hr], ['bp', c.vitals.bp], ['spo2', `${c.vitals.spo2}%`], ['rr', c.vitals.rr]].map(([k, v]) => (
            <span key={k} className="px-2.5 py-1 rounded-lg bg-slate-950/60 border border-slate-800 font-mono text-[11px] text-slate-400">
              <span className="text-slate-600">{L[k][lang]}</span> {v}
            </span>
          ))}
        </div>
      </div>

      {/* El electro. Las derivaciones sólo se resaltan DESPUÉS de responder: */}
      {/* marcarlas antes sería regalar la respuesta. */}
      <EcgSheet
        signal={signal}
        theme={theme}
        highlight={answered ? c.highlight : []}
        lang={lang}
        onLeadClick={setZoomLead}
      />

      {/* Pregunta y opciones */}
      {!answered && (
        <div className="space-y-2">
          <p className="text-slate-300 text-sm font-medium">{L.question[lang]}</p>
          {c.options.map((o) => (
            <button key={o.id} onClick={() => pick(o.id)}
              className="w-full text-left px-4 py-3 rounded-xl border border-slate-800 bg-slate-900/40 text-slate-300 hover:border-indigo-700/50 hover:bg-slate-800/60 active:scale-[0.99] transition-all text-sm">
              {o.label[lang]}
            </button>
          ))}
        </div>
      )}

      {/* Resultado y enseñanza */}
      {answered && (
        <div className="space-y-3">
          <div className={`rounded-xl border p-4 ${isRight ? 'border-emerald-700/50 bg-emerald-950/30' : 'border-rose-800/50 bg-rose-950/25'}`}>
            <div className="flex items-center gap-2 mb-1">
              {isRight ? <Check className="w-4 h-4 text-emerald-400" /> : <X className="w-4 h-4 text-rose-400" />}
              <span className={`font-bold text-sm ${isRight ? 'text-emerald-300' : 'text-rose-300'}`}>
                {isRight ? L.correct[lang] : L.incorrect[lang]}
              </span>
            </div>
            {!isRight && (
              <p className="text-slate-400 text-sm">
                {L.wasAnswer[lang]}: <span className="text-slate-200 font-medium">
                  {c.options.find((o) => o.id === c.answer).label[lang]}
                </span>
              </p>
            )}
          </div>

          <Block icon={Activity} tone="indigo" title={L.why[lang]} text={c.explain[lang]} />
          <Block icon={AlertTriangle} tone="amber" title={L.pitfall[lang]} text={c.pitfall[lang]} />
          <Block icon={Stethoscope} tone="sky" title={L.action[lang]} text={c.action[lang]} />

          <button onClick={next}
            className="w-full py-3.5 rounded-xl bg-indigo-700 hover:bg-indigo-600 active:scale-[0.99] text-white font-bold transition-all flex items-center justify-center gap-1">
            {L.next[lang]}
          </button>
        </div>
      )}

      {zoomLead && (
        <LeadZoom signal={signal} lead={zoomLead} theme={theme} lang={lang} onClose={() => setZoomLead(null)} />
      )}
    </div>
  );
}

function Block({ icon: Icon, tone, title, text }) {
  const tones = {
    indigo: 'border-indigo-900/50 bg-indigo-950/20 text-indigo-300',
    amber: 'border-amber-900/50 bg-amber-950/20 text-amber-300',
    sky: 'border-sky-900/50 bg-sky-950/20 text-sky-300',
  };
  return (
    <div className={`rounded-xl border p-4 ${tones[tone]}`}>
      <div className="flex items-center gap-2 mb-1.5">
        <Icon className="w-4 h-4" />
        <span className="font-mono text-[11px] uppercase tracking-widest font-semibold">{title}</span>
      </div>
      <p className="text-slate-300 text-sm leading-relaxed">{text}</p>
    </div>
  );
}
